import type { ContactFieldConfig, EditorState, EditorQuestion } from "@/types";

export const DEFAULT_CONTACT_FIELDS: ContactFieldConfig[] = [
  {
    key: "anrede",
    type: "radio",
    label: "Anrede",
    options: ["Herr", "Frau"],
    required: false,
    visible: false,
    sort_order: 0,
  },
  {
    key: "name",
    type: "text",
    label: "Vor- und Nachname",
    placeholder: "Max Mustermann",
    required: true,
    visible: true,
    sort_order: 1,
  },
  {
    key: "email",
    type: "email",
    label: "E-Mail-Adresse",
    placeholder: "max@beispiel.de",
    required: true,
    visible: true,
    sort_order: 2,
  },
  {
    key: "telefon",
    type: "tel",
    label: "Telefonnummer",
    placeholder: "+49 123 456789",
    required: false,
    visible: true,
    sort_order: 3,
  },
  {
    key: "plz",
    type: "plz",
    label: "Postleitzahl",
    placeholder: "12345",
    required: false,
    visible: false,
    sort_order: 4,
  },
];

export const DEFAULT_QUESTION: EditorQuestion = {
  _id: "default_q1",
  dbId: undefined,
  questionKey: "interesse",
  questionType: "single_choice",
  title: "Was interessiert Sie?",
  subtitle: "Bitte wähle eine Option.",
  visible: true,
  required: true,
  placeholder: "",
  maxLength: "",
  sliderMin: "0",
  sliderMax: "100",
  sliderStep: "1",
  sliderUnit: "",
  sliderDefault: "50",
  options: [
    { _id: "default_opt1", label: "Option A", value: "option_a", iconKey: "", iconUrl: "" },
    { _id: "default_opt2", label: "Option B", value: "option_b", iconKey: "", iconUrl: "" },
    { _id: "default_opt3", label: "Option C", value: "option_c", iconKey: "", iconUrl: "" },
  ],
};

export const DEFAULT_EDITOR_STATE: EditorState = {
  funnelName: "",
  funnelTitle: "Jetzt kostenloses Angebot anfordern",
  primaryColor: "#22c55e",
  textColor: "#1f2937",
  backgroundColor: "#ffffff",
  pageBackgroundColor: "transparent",
  font: "system",
  borderRadius: "0.5rem",
  maxWidth: "720px",
  contactFormSubtitle: "Wer soll das Angebot erhalten?",
  submitButtonLabel: "Anfrage absenden",
  successMessage: "Vielen Dank! Wir melden uns in Kürze bei Ihnen.",
  responseMessage: "Wir melden uns innerhalb von 24 Stunden bei Ihnen.",
  privacyText:
    "Mit dem Absenden stimme ich zu, per E-Mail und Telefon zu meiner Anfrage kontaktiert zu werden.",
  privacyPolicyUrl: "",
  footerText: "{{company_name}} · {{public_email}} · {{public_phone}}",
  answersOverviewLabel: "Ihre Angaben im Überblick:",
  footerCompanyName: "",
  footerEmail: "",
  footerPhone: "",
  notificationEmail: "",
  emailSenderLocal: "",
  isActive: true,
  questions: [DEFAULT_QUESTION],
  contactFields: DEFAULT_CONTACT_FIELDS,
};
