import type { ContactFieldConfig, EditorState, EditorQuestion } from "@/types";

export const DEFAULT_CONTACT_FIELDS: ContactFieldConfig[] = [
  {
    key: "anrede",
    type: "radio",
    label: "Anrede",
    options: ["Herr", "Frau"],
    required: false,
    visible: false,
    sort_order: 0,
  },
  {
    key: "name",
    type: "text",
    label: "Vor- und Nachname",
    placeholder: "Max Mustermann",
    required: true,
    visible: true,
    sort_order: 1,
  },
  {
    key: "email",
    type: "email",
    label: "E-Mail-Adresse",
    placeholder: "max@beispiel.de",
    required: true,
    visible: true,
    sort_order: 2,
  },
  {
    key: "telefon",
    type: "tel",
    label: "Telefonnummer",
    placeholder: "+49 123 456789",
    required: false,
    visible: true,
    sort_order: 3,
  },
  {
    key: "plz",
    type: "plz",
    label: "Postleitzahl",
    placeholder: "12345",
    required: false,
    visible: false,
    sort_order: 4,
  },
];

// Aufgabe 38: Factory für neue Custom-Multi-Field-Pages.
// Aufgabe 39: Welcome-Screen-Factory. Optionaler Intro-Step am Anfang des Funnels.
export function makeDefaultWelcomePage(): EditorQuestion {
  const rand = Math.random().toString(36).slice(2, 8);
  return {
    _id: `q_welcome_${Date.now().toString(36)}_${rand}`,
    dbId: undefined,
    kind: "welcome",
    questionKey: `welcome_${rand}`,
    questionType: "single_choice", // unused
    title: "Willkommen!",
    subtitle: "In den nächsten 2 Minuten beantwortest du ein paar Fragen — dann melden wir uns mit einem Angebot.",
    visible: true,
    required: false,
    placeholder: "",
    maxLength: "",
    sliderMin: "0",
    sliderMax: "100",
    sliderStep: "1",
    sliderUnit: "",
    sliderDefault: "50",
    options: [],
    dateMin: "",
    dateMax: "",
    dateDefault: "",
    numberMin: "",
    numberMax: "",
    numberStep: "1",
    numberDefault: "",
    numberUnit: "",
    checkboxLabel: "",
    welcomeButtonLabel: "Los geht's →",
  };
}

// Aufgabe 39: Adresse-Vorlage als Custom-Karte mit 4 vorausgewählten Feldern.
export function makeAddressCustomPage(): EditorQuestion {
  const rand = Math.random().toString(36).slice(2, 8);
  return {
    _id: `q_address_${Date.now().toString(36)}_${rand}`,
    dbId: undefined,
    kind: "custom",
    questionKey: `adresse_${rand}`,
    questionType: "single_choice",
    title: "Wie lautet deine Adresse?",
    subtitle: "Für ein passgenaues Angebot brauchen wir deine Anschrift.",
    visible: true,
    required: false,
    placeholder: "",
    maxLength: "",
    sliderMin: "0",
    sliderMax: "100",
    sliderStep: "1",
    sliderUnit: "",
    sliderDefault: "50",
    options: [],
    dateMin: "",
    dateMax: "",
    dateDefault: "",
    numberMin: "",
    numberMax: "",
    numberStep: "1",
    numberDefault: "",
    numberUnit: "",
    checkboxLabel: "",
    customFields: [
      { key: "strasse",  type: "text", label: "Straße",         placeholder: "Beispielstraße",  required: true, visible: true, sort_order: 0 },
      { key: "hausnr",   type: "text", label: "Hausnummer",     placeholder: "12a",             required: true, visible: true, sort_order: 1 },
      { key: "plz",      type: "plz",  label: "Postleitzahl",   placeholder: "12345",           required: true, visible: true, sort_order: 2 },
      { key: "ort",      type: "text", label: "Ort",            placeholder: "Berlin",          required: true, visible: true, sort_order: 3 },
    ],
  };
}

// Default-Layout: 2 Felder (Name + Email) als sinnvolle Startbasis. Tenant erweitert via Properties-Panel.
export function makeDefaultCustomPage(): EditorQuestion {
  const rand = Math.random().toString(36).slice(2, 8);
  return {
    _id: `q_custom_${Date.now().toString(36)}_${rand}`,
    dbId: undefined,
    kind: "custom",
    questionKey: `karte_${rand}`,
    questionType: "single_choice", // unused for custom — fallback to satisfy type
    title: "Neue Karte",
    subtitle: "",
    visible: true,
    required: false,
    placeholder: "",
    maxLength: "",
    sliderMin: "0",
    sliderMax: "100",
    sliderStep: "1",
    sliderUnit: "",
    sliderDefault: "50",
    options: [],
    dateMin: "",
    dateMax: "",
    dateDefault: "",
    numberMin: "",
    numberMax: "",
    numberStep: "1",
    numberDefault: "",
    numberUnit: "",
    checkboxLabel: "",
    customFields: [
      {
        key: "name",
        type: "text",
        label: "Vor- und Nachname",
        placeholder: "Max Mustermann",
        required: true,
        visible: true,
        sort_order: 0,
      },
      {
        key: "email",
        type: "email",
        label: "E-Mail-Adresse",
        placeholder: "max@beispiel.de",
        required: true,
        visible: true,
        sort_order: 1,
      },
    ],
  };
}

export const DEFAULT_QUESTION: EditorQuestion = {
  _id: "default_q1",
  dbId: undefined,
  kind: "question",
  questionKey: "interesse",
  questionType: "single_choice",
  title: "Was interessiert Sie?",
  subtitle: "Bitte wähle eine Option.",
  visible: true,
  required: true,
  placeholder: "",
  maxLength: "",
  sliderMin: "0",
  sliderMax: "100",
  sliderStep: "1",
  sliderUnit: "",
  sliderDefault: "50",
  options: [
    { _id: "default_opt1", label: "Option A", value: "option_a" },
    { _id: "default_opt2", label: "Option B", value: "option_b" },
    { _id: "default_opt3", label: "Option C", value: "option_c" },
  ],
  dateMin: "",
  dateMax: "",
  dateDefault: "",
  numberMin: "",
  numberMax: "",
  numberStep: "1",
  numberDefault: "",
  numberUnit: "",
  checkboxLabel: "Ja, ich stimme zu",
};

export const DEFAULT_EDITOR_STATE: EditorState = {
  funnelName: "",
  funnelTitle: "Jetzt kostenloses Angebot anfordern",
  primaryColor: "#22c55e",
  textColor: "#1f2937",
  backgroundColor: "#ffffff",
  pageBackgroundColor: "transparent",
  font: "system",
  borderRadius: "0.5rem",
  maxWidth: "720px",
  contactFormSubtitle: "Wer soll das Angebot erhalten?",
  submitButtonLabel: "Anfrage absenden",
  successMessage: "Vielen Dank! Wir melden uns in Kürze bei Ihnen.",
  responseMessage: "Wir melden uns innerhalb von 24 Stunden bei Ihnen.",
  privacyText:
    "Mit dem Absenden stimme ich zu, per E-Mail und Telefon zu meiner Anfrage kontaktiert zu werden.",
  privacyPolicyUrl: "",
  footerText: "{{company_name}} · {{public_email}} · {{public_phone}}",
  answersOverviewLabel: "Ihre Angaben im Überblick:",
  footerCompanyName: "",
  footerEmail: "",
  footerPhone: "",
  notificationEmail: "",
  emailSenderLocal: "",
  isActive: true,
  skipSubmitStep: false,
  redirectUrl: "",
  questions: [DEFAULT_QUESTION],
  contactFields: DEFAULT_CONTACT_FIELDS,
};
